// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader {
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String, dynamic> en = {
    "aboutUs": "About Us",
    "services": "Services",
    "work": "Work",
    "products": "Products",
    "home": "Home",
    "projects": "Projects",
    "contactUs": "Contact Us",
    "getAQuote": "Get a quote",
    "latest": "Latest",
    "client": "Client",
    "satisfaction": "Satisfaction",
    "employees": "Employees",
    "worldwide": "WorldWide",
    "completed": "Completed",
    "see": "See",
    "contact": "Contact",
    "contactTitle": "Let's have a chat",
    "address": "Address",
    "phone": "Phone",
    "email": "Email",
    "branchOffice": "Branch Office",
    "first": "First",
    "last": "Last",
    "name": "Name",
    "telephone": "Telephone",
    "message": "Message",
    "send": "Send",
    "our": "Our",
    "product": "Product",
    "noImage": "No Image",
    "all": "All",
    "construction": "Construction",
    "renovation": "Renovation",
    "project": "Project",
    "contactUsTitle": "Let's grab a cup of coffee and discuss the idea",
    "location": "Location",
    "keyPoints": "Key Points",
    "keyFeatures": "Key Features",
    "getAQuoteTitle": "Get quote of your pool project in few minutes",
    "shape": "Shape",
    "size": "Size",
    "depth": "Depth",
    "color": "Color",
    "yourPool": "Your Pool",
    "chooseTheShape": "Choose the shape of pool",
    "chooseTheDimensions": "Choose the dimensions of pool",
    "chooseTheDepth": "Choose the depth of pool",
    "chooseTheColor": "Choose the color of pool",
    "rectangle": "Rectangle",
    "square": "Square",
    "beach": "Beach",
    "bean": "Bean",
    "oval": "Oval",
    "lShape": "L-Shaped",
    "flatBottom": "Flat Bottom",
    "nextStep": "Next Step",
    "length": "Length",
    "width": "Width",
    "double": "Double",
    "dip": "Dip",
    "swim": "Swim",
    "enjoy": "Enjoy",
    "whiteLiner": "White Liner",
    "skyBlueLiner": "Sky Blue Liner",
    "sandLiner": "Sand Liner",
    "frenchBlueLiner": "French Blue Liner",
    "greenLiner": "Green Liner",
    "greyLiner": "Grey Liner",
    "enter": "Enter",
    "number": "Number",
    "submit": "Submit",
    "termsAndConditions":
        "By submitting this form I agree to the terms and conditions that are applied while dealing in this.",
    "personalInfo": "Personal Info",
    "enterInformation": "Please enter the following information",
    "aboutUsTitle": "Strategy led design in every detail",
    "servicesTitle": "Thought out to the Smallest detail",
    "interview": "Interview",
    "equipment": "Equipment"
  };
  static const Map<String, dynamic> fr = {
    "aboutUs": "Á Propos De Nous",
    "services": "Prestations De Service",
    "work": "Travailler",
    "product": "Produit",
    "home": "Domicile",
    "projects": "Projets",
    "contactUs": "Nous Contacter",
    "getAQuote": "Obtenir Un Devis",
    "latest": "Dernier",
    "client": "Client",
    "satisfaction": "Satisfaction",
    "employees": "Des employés",
    "worldwide": "À l'échelle mondiale",
    "completed": "Complété",
    "see": "Voir",
    "contact": "Contact",
    "contactTitle": "Discutons",
    "address": "Adresse",
    "phone": "Téléphoner",
    "email": "E-mail",
    "branchOffice": "Succursale",
    "first": "Première",
    "last": "Dernier",
    "name": "Nom",
    "telephone": "Téléphone",
    "message": "Message",
    "send": "Envoyer",
    "our": "Notre",
    "products": "Produits",
    "noImage": "Pas d'image",
    "all": "Tout",
    "construction": "Construction",
    "renovation": "Rénovation",
    "project": "Projet",
    "contactUsTitle": "Prenons une tasse de café et discutons de l'idée",
    "location": "Emplacement",
    "keyPoints": "Points Clés",
    "keyFeatures": "Principales Caractéristiques",
    "getAQuoteTitle":
        "Obtenez un devis de votre projet de piscine en quelques minutes",
    "shape": "Forme",
    "size": "Taille",
    "depth": "Profondeur",
    "color": "Couleur",
    "yourPool": "Votre Piscine",
    "chooseTheShape": "Choisissez la forme de la piscine",
    "chooseTheDimensions": "Choisissez les dimensions de la piscine",
    "chooseTheDepth": "Choisissez la profondeur de la piscine",
    "chooseTheColor": "Choisissez la couleur de la piscine",
    "rectangle": "Rectangle",
    "square": "Carré",
    "beach": "Plage",
    "bean": "Haricot",
    "oval": "ovale",
    "lShape": "En forme de L",
    "flatBottom": "Fond plat",
    "nextStep": "L'étape suivante",
    "length": "Longueur",
    "width": "Largeur",
    "double": "Double",
    "dip": "Tremper",
    "swim": "Baignade",
    "enjoy": "Prendre plaisir",
    "whiteLiner": "Doublure blanche",
    "skyBlueLiner": "Doublure bleu ciel",
    "sandLiner": "Revêtement de sable",
    "frenchBlueLiner": "Paquebot bleu français",
    "greenLiner": "Doublure verte",
    "greyLiner": "Doublure grise",
    "enter": "Entrer",
    "number": "Numéro",
    "submit": "Soumettre",
    "termsAndConditions":
        "En soumettant ce formulaire, j'accepte les termes et conditions qui s'appliquent lors de cette transaction.",
    "personalInfo": "Informations personnelles",
    "enterInformation": "Veuillez entrer les informations suivantes",
    "aboutUsTitle":
        "Conception axée sur la stratégie dans les moindres détails",
    "servicesTitle": "Pensé dans les moindres détails",
    "interview": "Interview",
    "equipment": "Équipement"
  };
  static const Map<String, Map<String, dynamic>> mapLocales = {
    "en": en,
    "fr": fr
  };
}
