// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsEQ8ZnTTqbd8U501SfhwgNdYOW7i0GvE',
    appId: '1:62971402408:web:4ec5af03eb02e8f2534a9d',
    messagingSenderId: '62971402408',
    projectId: 'pool-art-project',
    authDomain: 'pool-art-project.firebaseapp.com',
    storageBucket: 'pool-art-project.appspot.com',
    measurementId: 'G-6LEM071ZP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Hc4qfCR9esoNfWPL-dd20GkWlPvgoKw',
    appId: '1:62971402408:android:5adbfd06b73a8658534a9d',
    messagingSenderId: '62971402408',
    projectId: 'pool-art-project',
    storageBucket: 'pool-art-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYpbV3rRzv-6WpgD1_-fX-BKh89H3EyiM',
    appId: '1:62971402408:ios:be876046b92090b9534a9d',
    messagingSenderId: '62971402408',
    projectId: 'pool-art-project',
    storageBucket: 'pool-art-project.appspot.com',
    iosClientId:
        '62971402408-c3djvp4b92cm1th4lahg6t7ft795dv42.apps.googleusercontent.com',
    iosBundleId: 'fr.poolart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYpbV3rRzv-6WpgD1_-fX-BKh89H3EyiM',
    appId: '1:62971402408:ios:be876046b92090b9534a9d',
    messagingSenderId: '62971402408',
    projectId: 'pool-art-project',
    storageBucket: 'pool-art-project.appspot.com',
    iosClientId:
        '62971402408-c3djvp4b92cm1th4lahg6t7ft795dv42.apps.googleusercontent.com',
    iosBundleId: 'fr.poolart',
  );
}
